version: "3"
services:
  server:
    container_name: lazada-backend
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "127.0.0.1:4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001

